<script setup lang="ts">
import { computed, type Component } from 'vue'
import {
  X,
  Plus,
  RotateCcw,
  Sun,
  Moon,
  Loader2,
  GripVertical,
  GripHorizontal,
  Command,
  Copy,
  Trash2,
  Layers,
  ZoomIn,
  ZoomOut,
  Search,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Check,
  Circle,
  MoreHorizontal,
  Settings,
  Settings2,
  FileText,
  CheckSquare,
  Star,
  Info,
  Scissors,
  Clipboard,
  Download,
  StickyNote,
  Folder,
  ArrowLeft,
  Edit,
  LayoutGrid,
  User,
  Mail,
  Lock,
  Undo2,
  Redo2,
  Home,
  AlertCircle,
  CheckCircle,
  Upload,
  Eye,
  EyeOff,
  TrendingUp,
  Users,
  DollarSign,
  Activity,
  Zap,
  Heart,
  Bookmark,
  Share2,
  // Canvas tool icons
  MousePointer2,
  Hand,
  Square,
  Minus,
  ArrowRight,
  Pencil,
  Type,
  Palette,
  Grid,
  MoveHorizontal,
  // Text alignment icons
  AlignLeft,
  AlignCenter,
  AlignRight,
  // Module & settings icons
  BarChart2,
  Cable,
  Calendar,
  CalendarCheck,
  Clock,
  Columns,
  Database,
  Flame,
  Hash,
  Inbox,
  Link,
  List,
  ListTodo,
  Percent,
  Play,
  SlidersHorizontal,
  Target,
  Timer,
  Unlink,
  Volume2,
  type LucideIcon,
} from 'lucide-vue-next'

const iconComponents: Record<string, LucideIcon> = {
  x: X,
  plus: Plus,
  'rotate-ccw': RotateCcw,
  sun: Sun,
  moon: Moon,
  loader: Loader2,
  grip: GripVertical,
  'grip-vertical': GripVertical,
  'grip-horizontal': GripHorizontal,
  command: Command,
  copy: Copy,
  'trash-2': Trash2,
  layers: Layers,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  search: Search,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  check: Check,
  circle: Circle,
  'more-horizontal': MoreHorizontal,
  settings: Settings,
  'file-text': FileText,
  'check-square': CheckSquare,
  star: Star,
  info: Info,
  scissors: Scissors,
  clipboard: Clipboard,
  download: Download,
  'sticky-note': StickyNote,
  folder: Folder,
  'arrow-left': ArrowLeft,
  edit: Edit,
  'layout-grid': LayoutGrid,
  user: User,
  mail: Mail,
  lock: Lock,
  'undo-2': Undo2,
  'redo-2': Redo2,
  home: Home,
  'alert-circle': AlertCircle,
  'check-circle': CheckCircle,
  upload: Upload,
  eye: Eye,
  'eye-off': EyeOff,
  'trending-up': TrendingUp,
  users: Users,
  'dollar-sign': DollarSign,
  activity: Activity,
  zap: Zap,
  heart: Heart,
  bookmark: Bookmark,
  'share-2': Share2,
  // Canvas tool icons
  'mouse-pointer-2': MousePointer2,
  hand: Hand,
  square: Square,
  minus: Minus,
  'arrow-right': ArrowRight,
  pencil: Pencil,
  type: Type,
  palette: Palette,
  grid: Grid,
  'move-horizontal': MoveHorizontal,
  // Text alignment icons
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  // Module & settings icons
  'bar-chart-2': BarChart2,
  cable: Cable,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  clock: Clock,
  columns: Columns,
  database: Database,
  flame: Flame,
  hash: Hash,
  inbox: Inbox,
  link: Link,
  list: List,
  'list-todo': ListTodo,
  percent: Percent,
  play: Play,
  'settings-2': Settings2,
  'sliders-horizontal': SlidersHorizontal,
  target: Target,
  timer: Timer,
  unlink: Unlink,
  'volume-2': Volume2,
}

export type IconName = keyof typeof iconComponents

interface Props {
  icon: IconName | string
  size?: number
  strokeWidth?: number
}

const props = withDefaults(defineProps<Props>(), {
  size: 16,
  strokeWidth: 1.5,
})

const iconComponent = computed<Component | null>(() => {
  return iconComponents[props.icon] || null
})
</script>

<template>
  <component
    :is="iconComponent"
    v-if="iconComponent"
    :size="props.size"
    :stroke-width="props.strokeWidth"
    class="shrink-0"
  />
</template>
